apiVersion: v1
kind: Service

metadata:
  name: bgg-app-svc
  namespace: workshop02
  labels:
    name: bgg-app-svc

spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: bgg-app-pod
  ports:
  - port: 80
    targetPort: bgg-app-port