apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  namespace: default
  labels:
    name: fortune-pod
    version: "v1"
    owner: vernonwmk
spec:
  containers:
  - name: fortune
    image: chukmunnlee/fortune:v2
    imagePullPolicy: Always
    env: 
    - name: APP_PORT
      value: "3000"
    ports:
    - name: fortune-port
      containerPort: 3000
