apiVersion: apps/v1
kind: Deployment

metadata:
   name: bgg-db-deployment
   namespace: workshop02

spec:
   replicas: 1
   selector:
      matchLabels:
         app.kubernetes.io/name: bgg-db-pod

   template:
      metadata:
         name: bgg-db-pod
         labels:
            app.kubernetes.io/name: bgg-db-pod
            app.kubernetes.io/version: "v1"
            owner: engineering

      spec:
         volumes:
         - name: dbvol
           persistentVolumeClaim:
             claimName: bggdbpvc
         initContainers:
            - name: mydb-vol-scrub
              image: busybox
              command: ["/bin/sh", "-c", "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"]
              volumeMounts:
              - name: dbvol
                mountPath: /scrub
         containers:
         - name: bgg-db
           image: stackupiss/bgg-db:v1
           imagePullPolicy: Always
           ports:
           - name: mysql-port
             containerPort: 3306
           volumeMounts:
           - mountPath: /scrub
             name: dbvol
---

apiVersion: v1
kind: Service

metadata:
  name: bgg-db-svc
  namespace: workshop02
  labels:
    name: bgg-db-svc

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bgg-db-pod
  ports:
  - name: mysql-port-svc
    port: 3306
    targetPort: mysql-port
