apiVersion: autoscaling/v1

kind: HorizontalPodAutoscaler

metadata:
  name: bgg-app-scaler
  namespace: workshop02

spec:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bgg-app-deployment